services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      API_KEY: ${API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    command: ["python", "main.py"]
    restart: unless-stopped
